name: drhprediction
channels:
    - conda-forge
    - defaults
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - ipykernel
  - seaborn
  - pytorch
  - shap
  - xgboost
  - pip
  - pip: 
    - wget
